openapi: 3.1.0
info:
  title: EpsonConnectAPI
  version: '1.0'
  contact:
    email: foo@example.com
    name: 'Foo '
  description: ''
  summary: Epson Connect API （以降はAPIと記述）は、Epson Connectとつながっているデバイスに対して、外部から印刷等を制御・実行する手段を提供します。
servers:
  - url: 'http://xxxx'
paths:
  /api/1/printing/oauth2/token:
    post:
      summary: 認証
      operationId: post-printing-oauth2-token
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    token_type: Bearer
                    access_token: meJFiYNJHeH2D4rPLqqvkcr3BrUq4qhcYDkMPxd0y5Xms172iyPHLiAPcrw8vGMk
                    expires_in: 3600
                    refresh_token: 3vBbccxGKf2FAlWLwu8xWnjTNEImJQV6NTdSTCxl0cp91UXpysT1de0syQVgfafk
                    subject_type: ''
                    subject_id: da472a80320345b08761200bb8d9a72a
                properties:
                  token_type:
                    type: string
                    minLength: 1
                    description: “Bearer”固定
                  access_token:
                    type: string
                    minLength: 1
                    description: アクセストークン
                  expires_in:
                    type: number
                    description: |-
                      発行したアクセストークンの有効期限（秒）
                      “3600”（1時間）固定
                  refresh_token:
                    type: string
                    minLength: 1
                    description: |-
                      リフレッシュトークン
                      リフレッシュトークンは認証毎に新しく発行されて、新しく発行された順に5個まで利用可能
                  subject_type:
                    type: string
                    description: 不使用
                  subject_id:
                    type: string
                    minLength: 1
                    description: デバイスを識別するデバイスID
                required:
                  - token_type
                  - access_token
                  - expires_in
                  - refresh_token
                  - subject_type
                  - subject_id
              examples:
                example-1:
                  value:
                    token_type: Bearer
                    access_token: meJFiYNJHeH2D4rPLqqvkcr3BrUq4qhcYDkMPxd0y5Xms172iyPHLiAPcrw8vGMk
                    expires_in: 3600
                    refresh_token: 3vBbccxGKf2FAlWLwu8xWnjTNEImJQV6NTdSTCxl0cp91UXpysT1de0syQVgfafk
                    subject_type: ''
                    subject_id: da472a80320345b08761200bb8d9a72a
        '400':
          description: invalid_request
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            WWW-Authenticate:
              schema:
                type: string
              description: Basic realm="Token Generation" ※ステータスコード401 invalid client返却時のみ
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  error:
                    type: string
                    minLength: 1
                required:
                  - error
                x-examples:
                  example-1:
                    error: invalide client
              examples:
                username、passwordの形式が不正:
                  value:
                    error: invalid_request
                プリンターメールアドレスが不正、もしくはリモートプリント設定で、リモートプリントが不許可:
                  value:
                    error: invalid_grant
                grant_typeが不正:
                  value:
                    error: unsupported_grant_type
        '401':
          description: invalid_client
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            WWW-Authenticate:
              schema:
                type: string
              description: Basic realm="Token Generation" <br>※ステータスコード401 invalid client返却時のみ
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  error:
                    type: string
                    minLength: 1
                required:
                  - error
                x-examples:
                  example-1:
                    error: invalid_client
              examples:
                認証に失敗:
                  value:
                    error: invalid_client
        '500':
          description: server_error
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            WWW-Authenticate:
              schema:
                type: string
              description: Basic realm="Token Generation" <br>※ステータスコード401 invalid client返却時のみ
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  error:
                    type: string
                    minLength: 1
                required:
                  - error
                x-examples:
                  example-1:
                    error: server_error
              examples:
                予期しないエラー:
                  value:
                    error: server_error
      parameters:
        - schema:
            type: string
          in: query
          name: subject
          description: printer(固定文字列)を指定する
          required: true
        - schema:
            type: string
          in: header
          name: Authorization
          description: クライアントID※とクライアントシークレット※をBasic認証形式でエンコードしたもの ※ライセンス発行時に譲渡
          required: true
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/x-www-form-urlencoded; charset=utf-8
          required: true
      description: APIの利用許可を確認して、デバイスID、アクセストークン、リフレッシュトークンを発行します。
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties: {}
        description: |-
          ## 【認証】 
          grant_type=password&username=<プリンタのE-MailAddress>&password= 
          ※passwordは空文字を指定する

          ## 【アクセストークン再発行】
          grant_type=refresh_token&refresh_token=<取得したリフレッシュトークン> 
    parameters: []
  '/api/1/printing/printers/{device_id}/capability/{print_mode}':
    parameters:
      - schema:
          type: string
        name: device_id
        in: path
        required: true
        description: デバイスID (認証処理でsubject_idとして返却された値)
      - schema:
          type: string
        name: print_mode
        in: path
        required: true
        description: 印刷モード <br>“document”もしくは“photo”を指定<BR> document・・・文書を印刷する場合の印刷能力<BR> photo ・・・画像を印刷する場合の印刷能力
    get:
      summary: デバイス印刷能力取得
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    color_modes:
                      - color
                      - mono
                    media_sizes:
                      - media_size: ms_a3
                        media_types:
                          - media_type: mt_plainpaper
                            borderless: false
                            sources:
                              - rear
                              - front1
                              - front2
                              - front3
                              - front4
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: true
                      - media_size: ms_tabloid
                        media_types:
                          - media_type: mt_plainpaper
                            borderless: false
                            sources:
                              - rear
                              - front1
                              - front2
                              - front3
                              - front4
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: false
                      - media_size: ms_legal
                        media_types:
                          - media_type: mt_plainpaper
                            borderless: false
                            sources:
                              - rear
                              - front1
                              - front2
                              - front3
                              - front4
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: false
                      - media_size: ms_letter
                        media_types:
                          - media_type: mt_plainpaper
                            borderless: false
                            sources:
                              - rear
                              - front1
                              - front2
                              - front3
                              - front4
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: true
                      - media_size: ms_a4
                        media_types:
                          - media_type: mt_plainpaper
                            borderless: false
                            sources:
                              - rear
                              - front1
                              - front2
                              - front3
                              - front4
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: true
                          - media_type: mt_photopaper
                            borderless: false
                            sources:
                              - rear
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: false
                      - media_size: ms_b5
                        media_types:
                          - media_type: mt_plainpaper
                            borderless: false
                            sources:
                              - rear
                              - front1
                              - front2
                              - front3
                              - front4
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: false
                      - media_size: ms_a5
                        media_types:
                          - media_type: mt_plainpaper
                            borderless: false
                            sources:
                              - rear
                              - front1
                              - front2
                              - front3
                              - front4
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: false
                      - media_size: ms_a6
                        media_types:
                          - media_type: mt_plainpaper
                            borderless: false
                            sources:
                              - rear
                              - front1
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: false
                      - media_size: ms_postcard
                        media_types:
                          - media_type: mt_hagakiinkjet
                            borderless: false
                            sources:
                              - rear
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: false
                          - media_type: mt_hagaki
                            borderless: false
                            sources:
                              - rear
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: false
                properties:
                  color_modes:
                    type: array
                    description: |-
                      印刷可能なカラーモードを格納した配列  
                       「“color”,“mono”」もしくは「“mono”」  
                      color ・・・カラー印刷対応  
                      mono ・・・モノクロ(グレースケール)印刷対応
                    items:
                      type: object
                      properties:
                        '':
                          type: string
                  media_sizes:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    description: 用紙サイズごとの印刷能力オブジェクトを格納した配列
                    items:
                      type: object
                      properties:
                        media_size:
                          type: string
                          minLength: 1
                          description: |-
                            印刷可能な用紙サイズ  
                            詳細はAppendix B用紙サイズを参照
                        media_types:
                          type: array
                          uniqueItems: true
                          minItems: 1
                          description: 用紙種別ごとの印刷能力オブジェクトを格納した配列
                          items:
                            type: object
                            properties:
                              media_type:
                                type: string
                                minLength: 1
                                description: |-
                                  印刷可能な用紙種別  
                                  詳細はAppendix C用紙種別を参照
                              borderless:
                                type: boolean
                                description: |-
                                  フチなし印刷サポート可否  
                                  trueもしくはfalse
                              sources:
                                type: array
                                description: |-
                                  指定可能な給紙装置の配列
                                  詳細はAppendix D給紙装置を参照
                                items:
                                  type: object
                              print_qualities:
                                type: array
                                description: |-
                                  指定可能な印刷品質  
                                  “high”、“normal”もしくは“draft”  
                                  high ・・・きれい  
                                  normal ・・・標準  
                                  draft ・・・はやい  
                                items:
                                  type: object
                              2_sided:
                                type: boolean
                                description: |-
                                  両面印刷サポート可否  
                                  trueもしくはfalse
                            required:
                              - media_type
                              - borderless
                              - 2_sided
                      required:
                        - media_size
                required:
                  - color_modes
                  - media_sizes
              examples:
                印刷能力例:
                  value:
                    color_modes:
                      - color
                      - mono
                    media_sizes:
                      - media_size: ms_a3
                        media_types:
                          - media_type: mt_plainpaper
                            borderless: false
                            sources:
                              - rear
                              - front1
                              - front2
                              - front3
                              - front4
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: true
                      - media_size: ms_tabloid
                        media_types:
                          - media_type: mt_plainpaper
                            borderless: false
                            sources:
                              - rear
                              - front1
                              - front2
                              - front3
                              - front4
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: false
                      - media_size: ms_legal
                        media_types:
                          - media_type: mt_plainpaper
                            borderless: false
                            sources:
                              - rear
                              - front1
                              - front2
                              - front3
                              - front4
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: false
                      - media_size: ms_letter
                        media_types:
                          - media_type: mt_plainpaper
                            borderless: false
                            sources:
                              - rear
                              - front1
                              - front2
                              - front3
                              - front4
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: true
                      - media_size: ms_a4
                        media_types:
                          - media_type: mt_plainpaper
                            borderless: false
                            sources:
                              - rear
                              - front1
                              - front2
                              - front3
                              - front4
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: true
                          - media_type: mt_photopaper
                            borderless: false
                            sources:
                              - rear
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: false
                      - media_size: ms_b5
                        media_types:
                          - media_type: mt_plainpaper
                            borderless: false
                            sources:
                              - rear
                              - front1
                              - front2
                              - front3
                              - front4
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: false
                      - media_size: ms_a5
                        media_types:
                          - media_type: mt_plainpaper
                            borderless: false
                            sources:
                              - rear
                              - front1
                              - front2
                              - front3
                              - front4
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: false
                      - media_size: ms_a6
                        media_types:
                          - media_type: mt_plainpaper
                            borderless: false
                            sources:
                              - rear
                              - front1
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: false
                      - media_size: ms_postcard
                        media_types:
                          - media_type: mt_hagakiinkjet
                            borderless: false
                            sources:
                              - rear
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: false
                          - media_type: mt_hagaki
                            borderless: false
                            sources:
                              - rear
                              - auto
                            print_qualities:
                              - normal
                              - high
                            2_sided: false
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
        '404':
          description: printer_not_found
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  error:
                    type: string
                    minLength: 1
                required:
                  - error
                x-examples:
                  example-1:
                    error: printer_not_found
              examples:
                デバイスIDが不正もしくはEpson Connectから登録が削除されている:
                  value:
                    error: printer_not_found
      operationId: get-printing-printers-device_id-capability-print_mode
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: Bearer形式のアクセストークン
      description: 指定したデバイスの印刷能力情報を取得します。
  '/api/1/printing/printers/{device_id}/jobs':
    post:
      summary: 印刷設定
      operationId: post-printing-printers-device_id-jobs
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    id: 886ba15084e744c98d9913786bbaf1ac
                    upload_uri: 'https://example.com/c33fe124ef80c3b13670be27a6b0bcd7/v1/storage/PostData?Key=589cfa0b4207304d8c0c4cbe010af297ce4ae0b1393159533bca1e8d92c4427c2303795beb833848'
                properties:
                  id:
                    type: string
                    minLength: 1
                    description: 印刷ジョブID
                  upload_uri:
                    type: string
                    minLength: 1
                    description: 印刷するファイルをアップロードするURI
                required:
                  - id
                  - upload_uri
              examples:
                成功応答:
                  value:
                    id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
                    upload_uri: 'https://example.com/c33fe124ef80c3b13670be27a6b0bcd7/v1/storage/PostData?Key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
        '400':
          description: invalid_resource
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                印刷設定が不正:
                  value:
                    error: invalid_resource
        '404':
          description: printer_not_found
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  error:
                    type: string
                    minLength: 1
                required:
                  - error
                x-examples:
                  example-1:
                    error: string
              examples:
                デバイスIDが不正もしくは Epson Connectから登録が削除:
                  value:
                    error: printer_not_found
      description: 印刷設定を行い、印刷ジョブIDを発行します。
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: Bearer形式のアクセストークン
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/json; charset=utf-8
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  job_name: sample
                  print_mode: document
                  print_setting:
                    media_size: ms_a4
                    media_type: mt_plainpaper
                    borderless: false
                    print_quality: normal
                    source: front2
                    color_mode: mono
                    2_sided: none
                    reverse_order: false
                    copies: 1
                    collate: true
              properties:
                job_name:
                  type: string
                  minLength: 1
                  description: ジョブを識別するための名前（印刷対象のファイル名など）
                  maxLength: 256
                print_mode:
                  type: string
                  minLength: 1
                  description: |-
                    印刷モード  
                    document・・・文書を印刷する場合  
                    photo ・・・画像を印刷する場合
                  enum:
                    - document
                    - photo
                print_setting:
                  type: object
                  required:
                    - media_size
                    - media_type
                    - borderless
                    - print_quality
                    - source
                    - color_mode
                  description: 指定しない場合、Epson Connectで定義したデフォルトの印刷設定を適用
                  properties:
                    media_size:
                      type: string
                      minLength: 1
                      description: |-
                        印刷する用紙サイズ  
                        詳細はAppendix B用紙サイズを参照
                    media_type:
                      type: string
                      minLength: 1
                      description: |-
                        印刷する用紙種別  
                        詳細はAppendix C用紙種別を参照
                    borderless:
                      type: boolean
                      description: |-
                        印刷時のフチ有無  
                        true ・・・フチなし印刷  
                        false ・・・フチあり印刷
                    print_quality:
                      type: string
                      minLength: 1
                      description: |-
                        印刷時の印刷品質  
                        high ・・・きれい  
                        normal ・・・標準  
                        draft ・・・はやい
                      enum:
                        - high
                        - normal
                        - draft
                    source:
                      type: string
                      minLength: 1
                      description: |-
                        印刷時の給紙装置  
                        詳細はAppendix D給紙装置を参照
                    color_mode:
                      type: string
                      minLength: 1
                      description: |-
                        印刷時のカラーモード  
                        color ・・・カラー印刷  
                        mono ・・・モノクロ(グレースケール)印刷
                      enum:
                        - color
                        - mono
                    2_sided:
                      type: string
                      minLength: 1
                      description: |-
                        両面印刷  
                        none ・・・片面印刷  
                        long ・・・両面印刷（長辺綴じ）  
                        short・・・両面印刷（短辺綴じ）  
                        指定が無い場合、“none”
                      enum:
                        - none
                        - long
                        - short
                    reverse_order:
                      type: boolean
                      description: |-
                        逆順印刷の可否  
                        true ・・・最後のページから印刷  
                        false ・・・1ページ目から印刷  
                        指定が無い場合、false  
                        両面印刷に“long”もしくは“short”を指定した場合、false
                    copies:
                      type: number
                      description: |-
                        印刷部数  
                        1～99を指定可能  
                        指定が無い場合、1
                      maximum: 99
                      minimum: 1
                    collate:
                      type: boolean
                      description: |-
                        部単位印刷の可否  
                        true ・・・部単位で印刷  
                        false ・・・ページ単位で印刷  
                        指定が無い場合、true  
                        両面印刷に“long”もしくは“short”を指定した場合、true
              required:
                - job_name
                - print_mode
                - print_setting
        description: ''
    parameters:
      - schema:
          type: string
        name: device_id
        in: path
        required: true
        description: デバイスID (認証処理でsubject_idとして返却された値)
  Upload_URL:
    post:
      summary: 印刷ファイルアップロード
      operationId: post-printing-upload-file
      responses:
        '200':
          description: OK
        '404':
          description: アップロードURIに含まれるKeyが不正
        '413':
          description: アップロード容量の上限に到達
        '415':
          description: アップロードしたファイルが不正
      description: 印刷する文書、画像ファイルをアップロードします。
      parameters:
        - schema:
            type: string
          in: header
          name: Content-Length
          description: ファイルサイズ(単位：バイト) 印刷モードが“document”の場合・・・最大20MB 印刷モードが“photo”の場合 ・・・最大10MB
          required: true
        - schema:
            type: string
            enum:
              - application/octet-stream
              - image/jpeg
          in: header
          name: Content-Type
          required: true
          description: アップロードするファイル種別に応じたMIME-Type <br>application/octet-stream ・・・文書を印刷する場合 <br>image/jpeg ・・・画像を印刷する場合
        - schema:
            type: string
          in: query
          name: Key
          description: 印刷設定APIで取得したURIに含まれるKey
          required: true
        - schema:
            type: string
          in: query
          name: File
          description: 'アップロードするファイルの拡張子 “1.[拡張子]”で指定 <br>例）ファイル名が“sample.pdf”の場合、“1.pdf”を指定のこと'
          required: true
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: object
              properties: {}
        description: アップロードするファイルデータを指定します。
    parameters: []
  '/api/1/printing/printers/{device_id}/jobs/{job_id}/print':
    post:
      summary: 印刷実行
      operationId: post-printing-printers-device_id-jobs-job_id-print
      responses:
        '200':
          description: |-
            OK  
            正常に印刷されない場合、印刷ジョブ情報取得APIで印刷ジョブ状態を確認すること  
            ※印刷ジョブ状態については、Appendix E印刷ジョブ状態を参照
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '403':
          description: printjob_too_many
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                印刷待ちジョブが100個存在:
                  value:
                    error: printjob_too_many
        '404':
          description: |-
            printer_not_found
            job_not_found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                デバイスID不正もしくは Epson Connectから登録が削除されている:
                  value:
                    error: printer_not_found
                印刷ジョブIDが不正:
                  value:
                    error: job_not_found
        '405':
          description: command_not_allowed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                現在のステータスでは処理を呼び出し不可:
                  value:
                    error: command_not_allowed
      description: 指定した印刷ジョブの印刷を開始します。
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: Bearer形式のアクセストークン
          required: true
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/json; charset=utf-8
          required: true
    parameters:
      - schema:
          type: string
        name: device_id
        in: path
        required: true
        description: デバイスID (認証処理でsubject_idとして返却された値)
      - schema:
          type: string
        name: job_id
        in: path
        required: true
        description: 印刷ジョブID
  '/api/1/printing/printers/{device_id}/jobs/{job_id}/cancel':
    post:
      summary: 印刷キャンセル
      operationId: post-printing-printer-device_id-jobs-job_id-cancel
      responses:
        '200':
          description: OK
    parameters:
      - schema:
          type: string
        name: device_id
        in: path
        required: true
        description: デバイスID (認証処理でsubject_idとして返却された値)
      - schema:
          type: string
        name: job_id
        in: path
        required: true
  '/api/1/printing/printers/{device_id}/jobs/{job_id}':
    parameters:
      - schema:
          type: string
        name: device_id
        in: path
        required: true
      - schema:
          type: string
        name: job_id
        in: path
        required: true
    get:
      summary: 印刷ジョブ情報取得
      tags: []
      responses: {}
      operationId: get-printing-printers-device_id-jobs-job_id
  '/api/1/printing/printers/{device_id}':
    parameters:
      - schema:
          type: string
        name: device_id
        in: path
        required: true
        description: デバイスID (認証処理でsubject_idとして返却された値)
    get:
      summary: デバイス情報取得
      tags: []
      responses: {}
      operationId: get-printing-printers-device_id
    delete:
      summary: 認証取り消し
      operationId: delete-printing-device_id
      responses:
        '200':
          description: OK
  '/api/1/printing/printers/{device_id}/settings/notification':
    parameters:
      - schema:
          type: string
        name: device_id
        in: path
        required: true
    post:
      summary: 通知設定
      operationId: post-printing-printers-device_id-settings-notification
      responses:
        '200':
          description: OK
      description: ''
  '/api/1/scanning/scanners/{device_id}/destinations':
    parameters:
      - schema:
          type: string
        name: device_id
        in: path
        required: true
        description: デバイスID (認証処理でsubject_idとして返却された値)
    post:
      summary: スキャン宛先登録
      operationId: post-scanning-scanners-device_id-destinations
      responses:
        '200':
          description: OK
    get:
      summary: スキャン宛先一覧取得
      operationId: get-scanning-scanners-device_id-destinations
      responses:
        '200':
          description: OK
    put:
      summary: スキャン宛先更新
      operationId: put-scanning-scanners-device_id-destinations
      responses:
        '200':
          description: OK
    delete:
      summary: スキャン宛先削除
      operationId: delete-scanning-scanners-device_id-destinations
      responses:
        '200':
          description: OK
components:
  schemas: {}
  responses: {}
